spring.application.name=automation
spring.datasource.username=doadmin
spring.datasource.password=AVNS_gWlvsNXKm8krNDY_F0X
spring.datasource.url=jdbc:mysql://process-automation-db-do-user-19197166-0.g.db.ondigitalocean.com:25060/process_automation
#spring.datasource.url=jdbc:mysql://172.17.10.101:3306/automation?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
jwt.secret=c2VjcmV0S2V5Rm9yTXlKd3RUb2tlbiEyMzQ1Nc==
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.use-root-path=true

#
#username = doadmin
#password = AVNS_gWlvsNXKm8krNDY_F0X hide
#host = process-automation-db-do-user-19197166-0.g.db.ondigitalocean.com
#port = 25060
#database = defaultdb
